<head>
    <meta charset="UTF-8">
    <title>OFFICIAL INVENTORY CONTROL REPORT - {{ now()->format('M d, Y') }}</title>
<style>
    @page { margin: 15mm; }

    body {
        font-family: 'Helvetica', sans-serif;
        color: #000;
        margin: 0;
        line-height: 1.4;
    }

    /* 1. HIDE BUTTONS & FORCE FOOTER TO BOTTOM ON PRINT */
    @media print {
        .no-print { display: none !important; }

        /* Force the footer to stay at the bottom of the printed page */
        .page-footer-container {
            position: fixed;
            bottom: -10mm;
            left: 0;
            right: 0;
            height: 180px;
            background-color: white;
        }
    }

    /* 2. PDF ENGINE SPECIFIC POSITIONING */
    .pdf-fixed-footer {
        position: fixed;
        bottom: -10mm;
        left: 0;
        right: 0;
        height: 180px;
        background-color: white;
    }

    /* 3. NORMAL BROWSER PREVIEW (What you see on screen) */
    .preview-footer {
        width: 100%;
        margin-top: 50px;
    }

    .table-footer-space {
        height: 180px;
        border: none !important;
    }

    /* Official Header & Table Styles */
    .official-header { text-align: center; margin-bottom: 20px; }
    .official-header p { margin: 0; line-height: 1.1; font-size: 13px; }
    .official-header .republic { text-transform: uppercase; font-weight: bold; font-size: 15px; }
    .official-header .location { text-transform: uppercase; font-weight: bold; font-size: 13px; }
    .official-header .office { font-weight: bold; font-size: 17px; margin-top: 8px; display: block; }
    .report-title { text-align: center; font-weight: bold; font-size: 18px; text-transform: uppercase; text-decoration: underline; margin: 15px 0 5px 0; }
    .generation-meta { text-align: center; font-size: 11px; margin-bottom: 20px; }

    table.inventory-table { width: 100%; border-collapse: collapse; margin-top: 10px; }
    .inventory-table th { background-color: #f2f2f2; border: 1px solid #000; padding: 8px; font-size: 11px; text-align: left; text-transform: uppercase; }
    .inventory-table td { border: 1px solid #000; padding: 8px; font-size: 11px; }

    .sig-table { width: 100%; border: none; }
    .sig-box { width: 45%; text-align: center; border: none !important; padding: 0; vertical-align: bottom; }
    .sig-line { border-bottom: 1px solid #000; margin-top: 35px; margin-bottom: 5px; width: 80%; margin-left: auto; margin-right: auto; }
    .sig-name { font-weight: bold; text-transform: uppercase; font-size: 13px; margin: 0; }
    .footer-note { text-align: center; font-size: 9px; color: #555; border-top: 1px solid #ccc; padding-top: 10px; margin-top: 15px; }
</style>
</head>
<body>
    @if(!$isPdf)
        <div class="no-print" style="text-align: right; padding: 20px;">
            <button onclick="window.print()" style="padding: 10px 20px; background: #555; color: #fff; border: none; cursor: pointer; border-radius: 4px;">Print Report</button>
            <a href="{{ request()->fullUrlWithQuery(['download' => 1]) }}" style="padding: 10px 20px; background: #000; color: #fff; text-decoration: none; margin-left: 10px; border-radius: 4px; display: inline-block;">Download PDF</a>
        </div>
    @endif

    <div class="official-header">
        <p class="republic">Republic of the Philippines</p>
        <p class="location">Province of Bulacan</p>
        <p class="location">City of Meycauayan</p>
        <span class="office">Office of the City Veterinarian (PawCare)</span>
    </div>

    <div class="report-title">OFFICIAL VACCINE INVENTORY CONTROL REPORT</div>
    <div class="generation-meta">
        Date Generated: {{ now()->format('F d, Y h:i A') }}<br>
        Generated by: {{ auth()->user()->name ?? 'Main Admin' }}
    </div>

    <table class="inventory-table">
        <thead>
            <tr>
                <th>Vaccine Description</th>
                <th>Batch No.</th>
                <th>Date Received</th>
                <th>Expiry Date</th>
                <th>Current Stock</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($data as $vaccine)
            <tr>
                <td><strong>{{ $vaccine->name }}</strong></td>
                <td>{{ $vaccine->batch_no }}</td>
                <td>{{ \Carbon\Carbon::parse($vaccine->date_received)->format('M d, Y') }}</td>
                <td>{{ \Carbon\Carbon::parse($vaccine->expiry_date)->format('M d, Y') }}</td>
                <td style="text-align: center;">{{ $vaccine->stock }}</td>
                <td>{{ $vaccine->stock <= $vaccine->low_stock_threshold ? 'LOW STOCK' : 'AVAILABLE' }}</td>
            </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr>
                <td colspan="6" class="table-footer-space" style="border: none;"></td>
            </tr>
        </tfoot>
    </table>

    <div class="page-footer-container {{ $isPdf ? 'pdf-fixed-footer' : 'preview-footer' }}">
        <table class="sig-table">
            <tr>
                <td class="sig-box">
                    <p style="margin:0; font-size: 11px;">Prepared By:</p>
                    <div class="sig-line"></div>
                    <p class="sig-name">{{ auth()->user()->name ?? 'Main Admin' }}</p>
                    <p style="margin:0; font-size: 10px;">Clinic Staff / Data Officer</p>
                </td>
                <td style="width: 10%; border: none;"></td>
                <td class="sig-box">
                    <p style="margin:0; font-size: 11px;">Noted By:</p>
                    <div class="sig-line"></div>
                    <p class="sig-name">DR. IMELDA E. ARGUELLES</p>
                    <p style="margin:0; font-size: 10px;">City Veterinarian</p>
                </td>
            </tr>
        </table>
        <div class="footer-note">
            This is an official document generated by the PawCare System for the City of Meycauayan.
        </div>
    </div>
</body>
